/** Declaration file generated by dts-gen */

export function closing(el: any): any;

export function entity(el: any): any;

export function minify(el: any): any;

export function render(el: any, opt: any): any;

export namespace closing {
    const prototype: {
    };

}

export namespace entity {
    const prototype: {
    };

}

export namespace minify {
    const prototype: {
    };

}

export namespace render {
    const prototype: {
    };

}

